/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Approve specifies a configuration for a single approve.  The configuration for the approve plugin is defined as a list of these structures.
*/
export interface Approve {
    /**
    * IgnoreReviewState causes the approve plugin to ignore the GitHub review state. Otherwise: * an APPROVE github review is equivalent to leaving an \"/approve\" message. * A REQUEST_CHANGES github review is equivalent to leaving an /approve cancel\" message.
    */
    'ignoreReviewState'?: boolean;
    /**
    * IssueRequired indicates if an associated issue is required for approval in the specified repos.
    */
    'issueRequired'?: boolean;
    /**
    * LgtmActsAsApprove indicates that the lgtm command should be used to indicate approval
    */
    'lgtmActsAsApprove'?: boolean;
    /**
    * RequireSelfApproval requires PR authors to explicitly approve their PRs. Otherwise the plugin assumes the author of the PR approves the changes in the PR.
    */
    'requireSelfApproval'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ignoreReviewState",
            "baseName": "ignoreReviewState",
            "type": "boolean"
        },
        {
            "name": "issueRequired",
            "baseName": "issueRequired",
            "type": "boolean"
        },
        {
            "name": "lgtmActsAsApprove",
            "baseName": "lgtmActsAsApprove",
            "type": "boolean"
        },
        {
            "name": "requireSelfApproval",
            "baseName": "requireSelfApproval",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Approve.attributeTypeMap;
    }
}

