/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* AppSpec provides details of the metadata for an App
*/
export interface AppSpec {
    /**
    * A list of services that this App exposes
    */
    'exposedServices'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "exposedServices",
            "baseName": "exposedServices",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AppSpec.attributeTypeMap;
    }
}

