/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReplaceableSliceOfStrings } from './replaceableSliceOfStrings';

/**
* BranchProtectionContextPolicy configures required git provider contexts. Strict determines whether merging to the branch invalidates existing contexts.
*/
export interface BranchProtectionContextPolicy {
    'contexts'?: ReplaceableSliceOfStrings;
    /**
    * Strict overrides whether new commits in the base branch require updating the PR if set
    */
    'strict'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contexts",
            "baseName": "contexts",
            "type": "ReplaceableSliceOfStrings"
        },
        {
            "name": "strict",
            "baseName": "strict",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BranchProtectionContextPolicy.attributeTypeMap;
    }
}

