/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReplaceableSliceOfStrings } from './replaceableSliceOfStrings';

/**
* Brancher is for shared code between jobs that only run against certain branches. An empty brancher runs against all branches.
*/
export interface Brancher {
    'branches'?: ReplaceableSliceOfStrings;
    'skipBranches'?: ReplaceableSliceOfStrings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "branches",
            "baseName": "branches",
            "type": "ReplaceableSliceOfStrings"
        },
        {
            "name": "skipBranches",
            "baseName": "skipBranches",
            "type": "ReplaceableSliceOfStrings"
        }    ];

    static getAttributeTypeMap() {
        return Brancher.attributeTypeMap;
    }
}

