/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommitStatusDetails } from './commitStatusDetails';

/**
* CommitStatusSpec provides details of a particular commit status
*/
export interface CommitStatusSpec {
    'items': Array<CommitStatusDetails>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<CommitStatusDetails>"
        }    ];

    static getAttributeTypeMap() {
        return CommitStatusSpec.attributeTypeMap;
    }
}

