/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnvironmentRepository } from './environmentRepository';
import { PreviewGitSpec } from './previewGitSpec';
import { TeamSettings } from './teamSettings';

/**
* EnvironmentSpec is the specification of an Environment
*/
export interface EnvironmentSpec {
    'cluster'?: string;
    'kind'?: string;
    'label'?: string;
    'namespace'?: string;
    'order'?: number;
    'previewGitInfo'?: PreviewGitSpec;
    'promotionStrategy'?: string;
    'pullRequestURL'?: string;
    /**
    * RemoteCluster flag indicates if the Environment is deployed in a separate cluster to the Development Environment
    */
    'remoteCluster'?: boolean;
    'source'?: EnvironmentRepository;
    'teamSettings'?: TeamSettings;
    'webHookEngine'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        },
        {
            "name": "previewGitInfo",
            "baseName": "previewGitInfo",
            "type": "PreviewGitSpec"
        },
        {
            "name": "promotionStrategy",
            "baseName": "promotionStrategy",
            "type": "string"
        },
        {
            "name": "pullRequestURL",
            "baseName": "pullRequestURL",
            "type": "string"
        },
        {
            "name": "remoteCluster",
            "baseName": "remoteCluster",
            "type": "boolean"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "EnvironmentRepository"
        },
        {
            "name": "teamSettings",
            "baseName": "teamSettings",
            "type": "TeamSettings"
        },
        {
            "name": "webHookEngine",
            "baseName": "webHookEngine",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentSpec.attributeTypeMap;
    }
}

