/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExtensionParameter } from './extensionParameter';

/**
* ExtensionSpec provides details of an extension available for a team
*/
export class ExtensionSpec {
    'children'?: Array<string>;
    'description'?: string;
    'given'?: string;
    'name'?: string;
    'namespace'?: string;
    'parameters'?: Array<ExtensionParameter>;
    'script'?: string;
    'uuid'?: string;
    'version'?: string;
    'when'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<string>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "given",
            "baseName": "given",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<ExtensionParameter>"
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "when",
            "baseName": "when",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ExtensionSpec.attributeTypeMap;
    }
}

