/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProtectionPolicy } from './protectionPolicy';

/**
* GlobalProtectionPolicy defines the default branch protection policy for the scheduler
*/
export interface GlobalProtectionPolicy {
    'protectionPolicy'?: ProtectionPolicy;
    'protectTested'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "protectionPolicy",
            "baseName": "ProtectionPolicy",
            "type": "ProtectionPolicy"
        },
        {
            "name": "protectTested",
            "baseName": "protectTested",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GlobalProtectionPolicy.attributeTypeMap;
    }
}

