/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Adds and removes POSIX capabilities from running containers.
*/
export interface IoK8sApiCoreV1Capabilities {
    /**
    * Added capabilities
    */
    'add'?: Array<string>;
    /**
    * Removed capabilities
    */
    'drop'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "add",
            "baseName": "add",
            "type": "Array<string>"
        },
        {
            "name": "drop",
            "baseName": "drop",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1Capabilities.attributeTypeMap;
    }
}

