/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1Handler } from './ioK8sApiCoreV1Handler';

/**
* Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.
*/
export class IoK8sApiCoreV1Lifecycle {
    'postStart'?: IoK8sApiCoreV1Handler;
    'preStop'?: IoK8sApiCoreV1Handler;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "postStart",
            "baseName": "postStart",
            "type": "IoK8sApiCoreV1Handler"
        },
        {
            "name": "preStop",
            "baseName": "preStop",
            "type": "IoK8sApiCoreV1Handler"
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1Lifecycle.attributeTypeMap;
    }
}

