/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueLabel } from './issueLabel';
import { UserDetails } from './userDetails';

/**
* IssueSummary is the summary of an issue
*/
export interface IssueSummary {
    'assignees'?: Array<UserDetails>;
    'body'?: string;
    'closedBy'?: UserDetails;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'creationTimestamp'?: Date;
    'id'?: string;
    'labels'?: Array<IssueLabel>;
    'message'?: string;
    'state'?: string;
    'title'?: string;
    'url'?: string;
    'user'?: UserDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "assignees",
            "baseName": "assignees",
            "type": "Array<UserDetails>"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "closedBy",
            "baseName": "closedBy",
            "type": "UserDetails"
        },
        {
            "name": "creationTimestamp",
            "baseName": "creationTimestamp",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<IssueLabel>"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserDetails"
        }    ];

    static getAttributeTypeMap() {
        return IssueSummary.attributeTypeMap;
    }
}

