/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReplaceableMapOfStringString } from './replaceableMapOfStringString';

/**
* JobBase contains attributes common to all job types
*/
export interface JobBase {
    /**
    * Agent that will take care of running this job.
    */
    'agent': string;
    /**
    * Cluster is the alias of the cluster to run this job in. (Default: kube.DefaultClusterAlias)
    */
    'cluster'?: string;
    'labels'?: ReplaceableMapOfStringString;
    /**
    * MaximumConcurrency of this job, 0 implies no limit.
    */
    'maxConcurrency'?: number;
    /**
    * The name of the job. Must match regex [A-Za-z0-9-._]+ e.g. pull-test-infra-bazel-build
    */
    'name': string;
    /**
    * Namespace is the namespace in which pods schedule.   empty: results in scheduler.DefaultNamespace
    */
    'namespace'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agent",
            "baseName": "agent",
            "type": "string"
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "ReplaceableMapOfStringString"
        },
        {
            "name": "maxConcurrency",
            "baseName": "maxConcurrency",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return JobBase.attributeTypeMap;
    }
}

