/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* PipelineStructureStage contains the stage\'s name, one of either a reference to the Task corresponding to the stage if it has steps, a list of sequential stage names nested within this stage, or a list of parallel stage names nested within this stage, and information on this stage\'s depth within the PipelineStructure as a whole, the name of its parent stage, if any, the name of the stage before it in execution order, if any, and the name of the stage after it in execution order, if any.
*/
export interface PipelineStructureStage {
    'depth': number;
    'name': string;
    'next'?: string;
    'parallel'?: Array<string>;
    'parent'?: string;
    'previous'?: string;
    'stages'?: Array<string>;
    /**
    * Must have one of TaskRef+TaskRunRef, Stages, or Parallel
    */
    'taskRef'?: string;
    /**
    * Populated during pod discovery, not at initial creation time.
    */
    'taskRunRef'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "depth",
            "baseName": "depth",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "parallel",
            "baseName": "parallel",
            "type": "Array<string>"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "stages",
            "baseName": "stages",
            "type": "Array<string>"
        },
        {
            "name": "taskRef",
            "baseName": "taskRef",
            "type": "string"
        },
        {
            "name": "taskRunRef",
            "baseName": "taskRunRef",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PipelineStructureStage.attributeTypeMap;
    }
}

