/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Postsubmit } from './postsubmit';

/**
* Postsubmits is a list of Postsubmit job configurations that can optionally completely replace the Postsubmit job configurations in the parent scheduler
*/
export interface Postsubmits {
    /**
    * Items are the post submit configurations
    */
    'entries'?: Array<Postsubmit>;
    /**
    * Replace the existing entries
    */
    'replace'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<Postsubmit>"
        },
        {
            "name": "replace",
            "baseName": "replace",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Postsubmits.attributeTypeMap;
    }
}

