/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Brancher } from './brancher';
import { JobBase } from './jobBase';
import { RegexpChangeMatcher } from './regexpChangeMatcher';

/**
* Postsubmit runs on push events.
*/
export interface Postsubmit {
    'brancher'?: Brancher;
    'jobBase'?: JobBase;
    'regexpChangeMatcher'?: RegexpChangeMatcher;
    /**
    * Context is the name of the GitHub status context for the job.
    */
    'context': string;
    /**
    * Report will comment and set status on GitHub.
    */
    'report'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "brancher",
            "baseName": "Brancher",
            "type": "Brancher"
        },
        {
            "name": "jobBase",
            "baseName": "JobBase",
            "type": "JobBase"
        },
        {
            "name": "regexpChangeMatcher",
            "baseName": "RegexpChangeMatcher",
            "type": "RegexpChangeMatcher"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "string"
        },
        {
            "name": "report",
            "baseName": "report",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Postsubmit.attributeTypeMap;
    }
}

