/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Presubmit } from './presubmit';

/**
* Presubmits is a list of Presubmit job configurations that can optionally completely replace the Presubmit job configurations in the parent scheduler
*/
export interface Presubmits {
    /**
    * Items are the Presubmit configurtations
    */
    'entries'?: Array<Presubmit>;
    /**
    * Replace the existing entries
    */
    'replace'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<Presubmit>"
        },
        {
            "name": "replace",
            "baseName": "replace",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Presubmits.attributeTypeMap;
    }
}

