/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSpec } from './userSpec';

/**
* PreviewGitSpec is the preview git branch/pull request details
*/
export interface PreviewGitSpec {
    'appName'?: string;
    'applicationURL'?: string;
    'buildStatus'?: string;
    'buildStatusUrl'?: string;
    'description'?: string;
    'name'?: string;
    'title'?: string;
    'url'?: string;
    'user'?: UserSpec;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appName",
            "baseName": "appName",
            "type": "string"
        },
        {
            "name": "applicationURL",
            "baseName": "applicationURL",
            "type": "string"
        },
        {
            "name": "buildStatus",
            "baseName": "buildStatus",
            "type": "string"
        },
        {
            "name": "buildStatusUrl",
            "baseName": "buildStatusUrl",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserSpec"
        }    ];

    static getAttributeTypeMap() {
        return PreviewGitSpec.attributeTypeMap;
    }
}

