/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* PromoteWorkflowStep is the step of promoting a version of an application to an environment
*/
export interface PromoteWorkflowStep {
    'environment'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PromoteWorkflowStep.attributeTypeMap;
    }
}

