/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PromotePullRequestStep } from './promotePullRequestStep';
import { PromoteUpdateStep } from './promoteUpdateStep';

/**
* PromoteActivityStep is the step of promoting a version of an application to an environment
*/
export class PromoteActivityStep {
    'applicationURL'?: string;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'completedTimestamp'?: Date;
    'description'?: string;
    'environment'?: string;
    'name'?: string;
    'pullRequest'?: PromotePullRequestStep;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'startedTimestamp'?: Date;
    'status'?: string;
    'update'?: PromoteUpdateStep;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applicationURL",
            "baseName": "applicationURL",
            "type": "string"
        },
        {
            "name": "completedTimestamp",
            "baseName": "completedTimestamp",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "pullRequest",
            "baseName": "pullRequest",
            "type": "PromotePullRequestStep"
        },
        {
            "name": "startedTimestamp",
            "baseName": "startedTimestamp",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "update",
            "baseName": "update",
            "type": "PromoteUpdateStep"
        }    ];

    static getAttributeTypeMap() {
        return PromoteActivityStep.attributeTypeMap;
    }
}

