/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProtectionPolicy } from './protectionPolicy';

/**
* ProtectionPolicies defines the branch protection policies
*/
export interface ProtectionPolicies {
    'protectionPolicy'?: ProtectionPolicy;
    'replace'?: boolean;
    'entries'?: { [key: string]: ProtectionPolicy; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "protectionPolicy",
            "baseName": "ProtectionPolicy",
            "type": "ProtectionPolicy"
        },
        {
            "name": "replace",
            "baseName": "Replace",
            "type": "boolean"
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "{ [key: string]: ProtectionPolicy; }"
        }    ];

    static getAttributeTypeMap() {
        return ProtectionPolicies.attributeTypeMap;
    }
}

