/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BranchProtectionContextPolicy } from './branchProtectionContextPolicy';
import { Restrictions } from './restrictions';
import { ReviewPolicy } from './reviewPolicy';

/**
* ProtectionPolicy for merging.
*/
export interface ProtectionPolicy {
    /**
    * Admins overrides whether protections apply to admins if set.
    */
    'enforceAdmins'?: boolean;
    /**
    * Protect overrides whether branch protection is enabled if set.
    */
    'protect'?: boolean;
    'requiredPullRequestReviews'?: ReviewPolicy;
    'requiredStatusChecks'?: BranchProtectionContextPolicy;
    'restrictions'?: Restrictions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enforceAdmins",
            "baseName": "enforceAdmins",
            "type": "boolean"
        },
        {
            "name": "protect",
            "baseName": "protect",
            "type": "boolean"
        },
        {
            "name": "requiredPullRequestReviews",
            "baseName": "requiredPullRequestReviews",
            "type": "ReviewPolicy"
        },
        {
            "name": "requiredStatusChecks",
            "baseName": "requiredStatusChecks",
            "type": "BranchProtectionContextPolicy"
        },
        {
            "name": "restrictions",
            "baseName": "restrictions",
            "type": "Restrictions"
        }    ];

    static getAttributeTypeMap() {
        return ProtectionPolicy.attributeTypeMap;
    }
}

