/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* QuickStartLocation
*/
export interface QuickStartLocation {
    'excludes'?: Array<string>;
    'gitKind'?: string;
    'gitUrl'?: string;
    'includes'?: Array<string>;
    'owner'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "excludes",
            "baseName": "excludes",
            "type": "Array<string>"
        },
        {
            "name": "gitKind",
            "baseName": "gitKind",
            "type": "string"
        },
        {
            "name": "gitUrl",
            "baseName": "gitUrl",
            "type": "string"
        },
        {
            "name": "includes",
            "baseName": "includes",
            "type": "Array<string>"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return QuickStartLocation.attributeTypeMap;
    }
}

