/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* RegexpChangeMatcher is for code shared between jobs that run only when certain files are changed.
*/
export interface RegexpChangeMatcher {
    /**
    * RunIfChanged defines a regex used to select which subset of file changes should trigger this job. If any file in the changeset matches this regex, the job will be triggered
    */
    'runIfChanged'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "runIfChanged",
            "baseName": "runIfChanged",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegexpChangeMatcher.attributeTypeMap;
    }
}

