/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExternalPlugin } from './externalPlugin';

/**
* ReplaceableSliceOfExternalPlugins is a list of external plugins that can optionally completely replace the plugins in any parent SchedulerSpec
*/
export interface ReplaceableSliceOfExternalPlugins {
    'replace': boolean;
    'entries'?: Array<ExternalPlugin>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "replace",
            "baseName": "Replace",
            "type": "boolean"
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<ExternalPlugin>"
        }    ];

    static getAttributeTypeMap() {
        return ReplaceableSliceOfExternalPlugins.attributeTypeMap;
    }
}

