/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* ReplaceableSliceOfStrings is a slice of strings that can optionally completely replace the slice of strings defined in the parent scheduler
*/
export interface ReplaceableSliceOfStrings {
    /**
    * Items is the string values
    */
    'entries'?: Array<string>;
    /**
    * Replace the existing entries
    */
    'replace'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<string>"
        },
        {
            "name": "replace",
            "baseName": "replace",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ReplaceableSliceOfStrings.attributeTypeMap;
    }
}

