/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReplaceableSliceOfStrings } from './replaceableSliceOfStrings';

/**
* Restrictions limits who can merge Users and Teams entries are appended to parent lists.
*/
export interface Restrictions {
    'teams': ReplaceableSliceOfStrings;
    'users': ReplaceableSliceOfStrings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "teams",
            "baseName": "teams",
            "type": "ReplaceableSliceOfStrings"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "ReplaceableSliceOfStrings"
        }    ];

    static getAttributeTypeMap() {
        return Restrictions.attributeTypeMap;
    }
}

