/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceReference } from './resourceReference';

/**
* SourceRepositorySpec provides details of the metadata for an App
*/
export interface SourceRepositorySpec {
    'description'?: string;
    'org'?: string;
    /**
    * Provider stores the URL of the git provider such as https://github.com
    */
    'provider'?: string;
    /**
    * ProviderName is a logical name for the provider without any URL scheme which can be used in a label selector
    */
    'providerName'?: string;
    'repo'?: string;
    'scheduler'?: ResourceReference;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "org",
            "baseName": "org",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "providerName",
            "baseName": "providerName",
            "type": "string"
        },
        {
            "name": "repo",
            "baseName": "repo",
            "type": "string"
        },
        {
            "name": "scheduler",
            "baseName": "scheduler",
            "type": "ResourceReference"
        }    ];

    static getAttributeTypeMap() {
        return SourceRepositorySpec.attributeTypeMap;
    }
}

