/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CoreActivityStep } from './coreActivityStep';

/**
* StageActivityStep represents a stage of zero to more sub steps in a jenkins pipeline
*/
export interface StageActivityStep {
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'completedTimestamp'?: Date;
    'description'?: string;
    'name'?: string;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'startedTimestamp'?: Date;
    'status'?: string;
    'steps'?: Array<CoreActivityStep>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "completedTimestamp",
            "baseName": "completedTimestamp",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "startedTimestamp",
            "baseName": "startedTimestamp",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<CoreActivityStep>"
        }    ];

    static getAttributeTypeMap() {
        return StageActivityStep.attributeTypeMap;
    }
}

