/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* TeamStatus is the status for an Team resource
*/
export interface TeamStatus {
    'message'?: string;
    'provisionStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "provisionStatus",
            "baseName": "provisionStatus",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TeamStatus.attributeTypeMap;
    }
}

