/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Trigger specifies a configuration for a single trigger.  The configuration for the trigger plugin is defined as a list of these structures.
*/
export interface Trigger {
    /**
    * IgnoreOkToTest makes trigger ignore /ok-to-test comments. This is a security mitigation to only allow testing from trusted users.
    */
    'ignoreOkToTest'?: boolean;
    /**
    * JoinOrgURL is a link that redirects users to a location where they should be able to read more about joining the organization in order to become trusted members. Defaults to the Github link of TrustedOrg.
    */
    'joinOrgUrl'?: string;
    /**
    * OnlyOrgMembers requires PRs and/or /ok-to-test comments to come from org members. By default, trigger also include repo collaborators.
    */
    'onlyOrgMembers'?: boolean;
    /**
    * TrustedOrg is the org whose members\' PRs will be automatically built for PRs to the above repos. The default is the PR\'s org.
    */
    'trustedOrg'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ignoreOkToTest",
            "baseName": "ignoreOkToTest",
            "type": "boolean"
        },
        {
            "name": "joinOrgUrl",
            "baseName": "joinOrgUrl",
            "type": "string"
        },
        {
            "name": "onlyOrgMembers",
            "baseName": "onlyOrgMembers",
            "type": "boolean"
        },
        {
            "name": "trustedOrg",
            "baseName": "trustedOrg",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Trigger.attributeTypeMap;
    }
}

